# Generated by Django 5.2.5 on 2025-08-26 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_hunter', '0002_scanjob_result_alter_scanjob_id_alter_scanjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanjob',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vuln_hunter.user'),
        ),
    ]
