# Generated by Django 5.2.5 on 2025-08-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_hunter', '0003_alter_scanjob_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=100),
        ),
    ]
